use_frameworks!
platform :ios, '13.0'

target 'com.awareframework.ios.sensor.screen_Example' do
    
  pod 'com.awareframework.ios.sensor.locations'
  pod 'com.awareframework.ios.sensor.screen', :path => '../'

  target 'com.awareframework.ios.sensor.screen_Tests' do
    inherit! :search_paths

    
  end
end
